"""Add completed column to Task

Revision ID: 984ee44861bd
Revises: 
Create Date: 2023-12-04 17:53:57.679605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '984ee44861bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
